### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by mvayngrib** [capriza/socketgd#2]
i'd be much more comfortable using this if there were at least some basic ones :)

btw, thanks for making this!

**Comment by fujifish** [comment]
Point taken. Will do my best to write some test when time permits.

For now you can feel comfortable with this as it's been successfully used in production for some time now.

**Comment by fujifish** [comment]
Added basic tests, hopefully should suffice for now.

**Comment by mvayngrib** [comment]
@fujifish awesome, thanks!
