### ISSUE TITLE
[clarification] server example

### ISSUE THREAD

**Issue by mvayngrib** [capriza/socketgd#3]
in the server-side example in the readme, you have:

``` js
io.on('connection', function(socket) {

  // set the underlying socket in socketgd.
  // if any already acked messages arrive they will be silently discarded
  socketgd.setSocket(socket);
```

as far as I understand, every connection will have its own socket, so you'd have to have one SocketGD instance per connection. Let me know if that's incorrect? If i'm right and that's what you meant when you wrote the example, let's add a comment to prevent this misconception :)

**Comment by fujifish** [comment]
Every connection should have a separate socketgd wrapping it, however the server side maintains the id of the last acked message so it can discard any messages it has already acked.
If you create a completely new socketgd wrapper for **reconnecting** sockets you'll lose the last acked message id, and messages might get handled by the application twice.

There are two ways to handle this:

1. set the underlying socket.io socket within the same socketgd wrapper (as in the example, though I agree it;s not the best real-life scenario)
2. call `setLastAcked` on a new socketgd instace

Either way, you'll have to associate the last acked message id with the incoming socket. We do it using a query parameter of our own holding a uuid

**Comment by fujifish** [comment]
Also, if you create a new SocketGD for a connecting client socket you might end up losing any messages sent from the server side that have not been acked by the client, so using the same SocketGd object is crucial.

If there is something else that's missing from the docs, please be more specific, it should all be there already.
